name: Deploy to Webcup Server

on:
  push:
    branches:
      - master 

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          pass: ${{ secrets.FTP_PASSWORD }} 
          port: 22
          remoteDir: ~/public_html/m0nobloc/
  docker-build:
    runs-on: ubuntu-latest
    needs: ftp-deploy
    steps:  
      - name: Ssh
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  

      - name: Docker Run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.FTP_HOST }}  
          username: ${{ secrets.FTP_USERNAME }}  
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            echo "Executing Docker Script"
            ${{ secrets.DOCKER_SCRIPT }}  
            echo "Done."
